### PR TITLE
WIP: Update Iquidus Explorer, fix vulnerabilities, add new features #252

### PR DESCRIPTION
**Pull request by uaktags**
There's a ton of commits not shown from my remote git repo:

- Added new themes from bootswatch and removed the obsolete ones
- Updated deps to mitigate vulnerabilities found from npm audit.
- Migrated from jade to pug due to deprecation
- As my repo is a combination of Iquidus and Ciquidus, I removed chaincoin references to go back to a vanilla state (note should be made later of their use and inclusion before Pull Request is merged).
- Worked on peers sync issue due to #253 
- Added server-side processing for the latest transactions for #256 (this still needs work as I think it's ugly showing the collection.count. Haven't spent enough time looking at DataTables to figure out how to avoid that.)
- Removed the hardcoding of Crypto-API commands and instead went with a modular design. See coin_commands folder for more information.
- Removed hardcoding of the social links and instead opted for creating an array that can be dynamically sized and not need recoding to happen.

Probably more. This also saw the creation of https://github.com/uaktags/Bitcoin-Node-Api due to vulnerabilities with express 3.x.

Shoutout to @suprnurd for his Ciquidus fork as that was the version I started tinkering with due to the Masternode inclusion. 

Later I do want to tackle https://github.com/SigwoTechnologies/explorer for their expanded Masternode views and graphs. According to #134 this appears to be the best example of this but I've yet to test it and like me they didn't do a native fork on Github, so I can't see the exact changes and will need to nitpick.

### CODE REVIEW

**Comment by uaktags** [comment]
I found that /tx/:hash can get really bogged down since it's returning all records. However, due to #249 there wasn't really a way to do serverside processing in a clean manner like I was able to do with the get_last_txes. So I created a method to do this. It works, but doesn't mean it's great. I really need to make sure we come back to this and fix it later:
https://github.com/iquidus/explorer/pull/257/commits/bc25fe0cc3fba22ca5ec1b70da7517a1f29649cc#diff-0364f57fbff2fabbe941ed20c328ef1aR102.

This is all done via an aggregate:
```
 Address.aggregate([{
        $lookup: {
          from: "txes",
          localField: "txs.addresses",
          foreignField: "txid",
          as: "txs"
        }
  
      },
      {
        $match: {
          "a_id": hash
        }
      },
      {
        $project: {
          totalTxes: {
            $size: "$txs"
          },
          txes: "$txs",
          type: "$type",
          timestamp: "$txs.timestamp"
        }
      }
    ], function (err, count) {
      if (err) {
        return cb(err);
      } else {
        return cb(count[0]);
      }
    });
```


***yikes***

**Comment by uaktags** [comment]
Started an import of DSTRACoin/diquidus fork since it too follows some ideas from me (updated to pug, used ciquidus as base, etc). Their fork also brought forth better language support which should be nice. Currently commit 23c7479 is partially coded with the i18 support. My main focus was going through all of the libraries and make sure that I didn't have any missing functions from that fork.

**Comment by Merratzz** [comment]
For me,  didn’t work with latest tree from you i got follow. 

npm install
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: bitcoin-node-api@git+http://git@github.com/uaktags/Bitcoin-Node-Api.git.
npm ERR! package.json npm can't find a package.json file in your current directory.

Help, please...

**Comment by uaktags** [comment]
@Merratzz try npm install again. I had an error in my package.json file in the Bitcoin-Node-Api which I just fixed (missing comma). Just ran through a clean install on CentOS and Windows successfully.

**Comment by Merratzz** [comment]
@uaktags Ok now it does, thanks. But next  i am got https://github.com/iquidus/explorer/issues/118  
block.tx.lenght  cannot read . Must Daemon running locale? Can it be if wrong genesis and genesis tx, on yiimp i take the tx from block 1 , and genesis is block 0 on yiimp taken from yiimp explorer correctly? i used  f9120b3....

**Comment by uaktags** [comment]
You'll want gensis to be block 0 and tx to be the tx from block 0. What country are you working with? It may be easier for me to help.

**Comment by Merratzz** [comment]
Ok setuo is now good i view just that https://www.youtube.com/watch?v=laeV2slJgc8, all should be right.

Wallet is running an setup correctly with all used flags server=1
daemon=1 txindex=1  rpcport= 

But if i do nmp startgot same error as many other users also reported. 

Error  --> Cannot read property block.tx.lenght of undefined.    block.tx.lenght   What do is wrong?

**Comment by uaktags** [comment]
If you're getting things like no blocks, error look in console, etc, then that tells me you probably have an issue with your RPC connection.

Try doing this:
curl --user <username_for_rpc> --data-binary '{"jsonrpc":"1.0","id":"curltext","method":"getinfo","params":[]}' -H 'content-type:text/plain;' http://<IP of your Daemon>:<PORT>

Run this from whereever the nodejs server is. You should get your getinfo response back.

Also, what coin are you using so I can test? Nothing that I did should have changed these setup procedures. Yes I have a constantly running example of my latest commit running at all times. Code works just fine with non-masternodes as well (since all I did was add the functionality on top of the base functionality)

**Comment by uaktags** [comment]
Also, it may be beneficial if you use the main iquidus explorer, rather than a WIP pull request. That may prove more stable. Once the pull request is finalized, i'll remove the WIP nomenclature, and you can just simply pull the update and use it since the PR is based off of the main branch anyhow.

**Comment by Merratzz** [comment]
Ok thanks for fast reply. Yesterday hole dayi fork orginall lquidus and copie all ingrate all your changes from first commit to get, the original master running, but i got at last always the same issue. 

nmp start, is ok ,  localhost:3001  is there , but no connection to wallet

sudo node scripts/sync.js index update   -->  give me  that

¨¨
script launched with pid: 10667
(node:10667) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
Update Stats Completed.
(node:10667) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
/home/xelectrum/explorer/lib/database.js:657
              lib.syncLoop(block.tx.length, function (subloop) {
                                    ^

TypeError: Cannot read property 'length' of undefined
    at /home/xelectrum/explorer/lib/database.js:657:37
    at Request._callback (/home/xelectrum/explorer/lib/explorer.js:122:14)
    at Request.self.callback (/home/xelectrum/explorer/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/xelectrum/explorer/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/xelectrum/explorer/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
¨¨

Its for my own coin.  https://github.com/BITRY/PRUX-Wallet   ultra fast and rare

Ok done with that, from vm machine where i installed explorer;  I do with follow code successful talk with rpc

curl --data-binary '{"jsonrpc":"1.0","id":"curltext","method":"getinfo","params":[]}' -H 'content-type:text/plain;' http://myrpcusername:myrpcpass@myhost:8739/ -o 123.txt

Give me in my 123.txt  follow output

{"result":{"version":1010000,"protocolversion":60001,"walletversion":60000,"balance":0.00000000,"blocks":8686734,"connections":1,"proxy":"","difficulty":1.70216358,"testnet":false,"keypoololdest":1547809761,"keypoolsize":101,"paytxfee":0.00000000,"mininput":0.00010000,"errors":""},"error":null,"id":"curltext"}

Is that ok?

**Comment by uaktags** [comment]
I was more suggesting that you test original vanilla iquidus without integrating my WIP PullRequest to ensure that iquidus is working as expected and you have your settings.json setup correctly. Please try that, and if you find that the issue is only with my fork, then create an Issue on my Fork's repo. I'm going to continue to focus this WIP PullRequest on commenting features and updates, rather than servicing bug issues.

**Comment by uaktags** [comment]
@Merratzz  https://github.com/uaktags/explorer/issues/3
----------------------------
Updates still to come.
[x]Claim form should be just about finished with its logic. 
[ ]Settings.json.template needs to be updated
[ ]Bring a wider range of popular coin_command examples
[ ] Refactor code to clean up all new additions.

**Comment by Merratzz** [comment]
Where can i got ""original vanilla iquidus""  without vulnerabilities error , or i have to create? Link?

**Comment by uaktags** [comment]
You get the original vanilla iquidus from iquidus/explorer. There is no official version released by Iquidus with the npm vulnerability. That's why this Work-In-Progress Pull Request exists.

Please use issues and follow the previously noted information. Trying to keep this PR clean to keep things progressing. Your issue has been resolved, I'm going to continue focusing on development in this PR only. Communication can follow in the proper methods.

**Comment by uaktags** [comment]
d352a7b is the start of cleaning up the upgrade path (still not complete nor finished). Due to the issue brought up by issue uaktags/#3 as described with the above comments, I created a simple script in the scripts folder to check the settings.json file for any edits that are needed (a number of them are).

This script can be updated as settings are added/removed and provide basic information on how to deal with it. The settings.json.template and proper documentation will always beat out anything this simple script will do, but it's nice to run it against your settings.json file. Here's an example output:

```
 node .\scripts\upgrade-settings-check.js
Checking if all values in Settings have the first letter lowercased.
+-+-+-+-+
+-+-+-+-+
Finsihed checking casings.
+-+-+-+-+
+-+-+-+-+Checking if any settings have been changed+-+-+-+-+
+-+-+-+-+
'locale' has been changed from 'locale' to 'language'. Please update accordingly.
Finished checking for changed settings.
+-+-+-+-+
+-+-+-+-+Checking for any removed settings.+-+-+-+-+
+-+-+-+-+
'locale' has been removed from Settings.json and is no longer valid
'twitter' has been removed from Settings.json and is no longer valid
'facebook' has been removed from Settings.json and is no longer valid
'googleplus' has been removed from Settings.json and is no longer valid
'youtube' has been removed from Settings.json and is no longer valid
'bitcointalk' has been removed from Settings.json and is no longer valid
'github' has been removed from Settings.json and is no longer valid
'slack' has been removed from Settings.json and is no longer valid
'website' has been removed from Settings.json and is no longer valid
'labels' has been removed from Settings.json and is no longer valid
Finished checking for removed Settings
+-+-+-+-+
+-+-+-+-+Checking for new Settings that aren't present yet+-+-+-+-+
+-+-+-+-+
'language' has been added to Settings.json and was not found in your settings configuration. Please add it according to the template example.
'social' has been added to Settings.json and was not found in your settings configuration. Please add it according to the template example.
'commands_needed' has been added to Settings.json and was not found in your settings configuration. Please add it according to the template example.
'peers' has been added to Settings.json and was not found in your settings configuration. Please add it according to the template example.
'decimal_places' has been added to Settings.json and was not found in your settings configuration. Please add it according to the template example.
Finished checking for new settings
+-+-+-+-+
+-+-+-+-+
```

**Comment by Merratzz** [comment]
Ok yesterday is setup a running ABE, but liquidus is much more usable. Sorry for communication over here.
Oh nice, you make me happy, thanks a lot, you checkup script does it with latests commit d352a7b, Now frontend http running on :3001  and it has also connection to wallet. Ok reindex first and after update, i does snyc now :+1: . How to set http without Master-node displayed. My coin is without masternode

**Comment by uaktags** [comment]
I don't want to seem rude, but I will not be answering any more questions in this forum. 
```
Work-In-Progress Pull Request
```
```
I'm going to continue focusing on development in this PR only. Communication can follow in the proper methods.
```
```
Please use issues and follow the previously noted information. Trying to keep this PR clean to keep things progressing.
```

**Comment by nashsclay** [comment]
I have been adding scripts for new install but will test with these changes you are proposing.

**Comment by uaktags** [comment]
Great, can't wait to see then @nashsclay! 

--------------------------

I haven't updated anything in a while as I've been trying to get clusterization of the sync working, but running into issues with RPC timeouts.

Basically the idea I started rolling with was use Cluster to spawn workers to collect all of the txid's for every block from start to stats.last. So say you do a reindex (start = 0) and the most recent block is 1000. 

Spawn x workers based on number of cpus free, divide the work between the workers, getblockhash per block, then get_block to record the txids and save them to an Array for later. Now once all of these workers are done, they're exited/killed and a new cluster is created. 

Out of the 1000blocks, we may have let's say 4000 transactions, we can divide those txes evenly by all of the workers.

In theory, now we have multiple workers, evenly knocking through transactions regardless of blocks. 

In practice, however, there's many flaws with either my implementation, or with how Javascript itself functions with callbacks and clustering. Since there's no way to pool the transactions, to identify that WorkerA may be working TXID11111, so WorkerB should start on TXID11112, and so on. The array idea sucks, and even if all that was good, hitting the daemon on RPC so rapidly, I've consistently started to see the times go from low MS to up to 10seconds to respond after 1600transactions. Since there's no way to sleep or slow down this process, we're kinda stuck with it failing after about 20seconds of running through 1600txes.

**Comment by th3geek** [comment]
@uaktags instead of storing the txids in an array why not throw them in a /tmp text file with a limit of say 1000 txids per file (random smallish number).  As the workers open these /tmp files they .lock the file preventing any of the other workers from accessing their txids until they've had a chance to lookup all txids and delete the /tmp file.

As far as slowing down how fast they hit the RPC daemon, wouldn't a quick and dirty renice to 1 do the trick for the time being?  Mind sharing the code you've been working with?

**Comment by uaktags** [comment]
I need help from anyone willing on 4e77b7c to get clustering working. If you see my https://github.com/uaktags/explorer/issues/14 you'll see that I'm pretty close to getting a huge speed boost by using clustering and bitcoin-core rather than just doing everything to the explorer and have it parse it to bitcoin-node-api. But I'm having erratic behavior with the workers and saving transactions. Sometimes I'm only ~10txes off, sometimes I'm more, and sometimes i'm 100% on point. 

@M-Shahbaz and @SharkWipf , perhaps you guys have some ideas of what I'm doing wrong in that.

**Comment by uaktags** [comment]
I think I may have resolved this already. testing now.

**Comment by uaktags** [comment]
https://github.com/uaktags/explorer/issues/14#issuecomment-488784300

**Comment by SharkWipf** [comment]
Sorry, I was out watching Endgame all day, so only seeing this now.  
I'm afraid I'm not familiar enough with either the blockchain intricacies nor the Iquidus code to be able to provide meaningful insight here, I only dug around in the Iquidus code just deep enough to find what was hampering my performance last time around.  
Glad to see you're making progress though, the results are looking really promising. Nice work!

**Comment by uaktags** [comment]
No worries, I think I'm almost complete with the clustering, just need a way of making sure the workers don't crap out half way through.

**Comment by uaktags** [comment]
I think with 68c4996 I'm just about done with the clustering. Right now I can get it to update and reindex correctly, but I'm messing up somewhere at the very end. 

Basically my issue right now is not correctly identifying the last block to try to grab. So the last worker sometimes gets hit with a block-height that doesn't actually exist. This wouldn't be a problem, but database.js's update_tx_db has a Stats.update command in there that updates the last value.

I've put in a solution with it, but right now, every fix I make seems to make the house of cards become even more unstable. I need to just properly refactor sync.js and database.js to get the end result stable.

Currently have bitcoin syncing. Daemon itself is only up to height 378432 so that's like 2016. Going to see how long it takes iquidus to get that high atleast on a reindex.

The benefit, though, is my work in already refactoring database.js for https://github.com/uaktags/explorer/issues/13 has given me the option for removing bitcoin-node-api from the equation. Without bitcoin-node-api, I can now run ``node scripts/sync.js index update`` from a remote server as it no longer needs to communicate with the Explorer. Instead it just directly communicates with the wallet's daemon. This means solutions can be made to work on my ``benchmark-cluster.js`` and modify it to have a custom start and stop point, so you can in theory cluster this out to multiple VMs.
1 VM is your Iquidus Explorer website + possibly mongodb
1 VM is your wallet's daemon
1+ VMs are your syncing vms.
These sync vms could in theory then focus on indexing 100k blocks each (you'll need 5 of them in BTC's case), with 1 process per CPU thread available. Then once syncing is finished, delete your unneeded vms and leave only 1 to keep doing the sync update script.

**Comment by uaktags** [comment]
https://github.com/uaktags/explorer/tree/cluster-sync is where the current branch that's attacking the clustering portion is taking place. If anyone has good experience with clustering or can help where I'm failing, please by all means do.

The current issue I'm needing to solve is the fact that I'm hitting the daemon so hard that after some time it causes the daemon to produce ECONNREFUSED which then kills the workers. I've started monitoring the workers and can restart/refork new workers as needed after killing any that are stalled out, but I'm leaking memory and end up really slowing down the process until it all fails.

**Comment by iquidus** [comment]
@uaktags check your invites, added you to collaborators.

**Comment by uaktags** [comment]
Very cool, thank you!

**Comment by RottenCoin** [comment]
Hi. I updated "font awesome" to get Discord logo, but I was too lazy to change all the links , so just modified existing ones to what I needed. http://explorer.omegablockchain.net/

**Comment by TheHolyRoger** [comment]
Too much in one PR...

**Pull request closed without merging**
