### PR TITLE
Network: Add tab with information to easily get addnode information for Wallets

### PR DESCRIPTION
**Pull request by TheHolyRoger**
As requested.

Network: Add tab with information to easily get addnode information for Wallets.

### CODE REVIEW

**Comment by TheHolyRoger** [comment]
@Altcoin-Cash @lyricidal @minkcrypto @cryptozeny

If any of you get a chance to test this PR it would be appreciated! Not massive changes so want to merge this to master soon.

**Comment by cryptozeny** [comment]
could you attach the screenshot? 😉

**Comment by TheHolyRoger** [comment]
net

**Comment by cryptozeny** [comment]
it seems kooooool

**Comment by TheHolyRoger** [comment]
@altmarkets

**Comment by uaktags** [comment]
Vulcano is currently downloading the blockchain (1y 18wk behind) and will then spin up a test of this for ya. Don't see any reason why this would not work though. :+1:

**Comment by TheHolyRoger** [comment]
Nice cheers @uaktags ! Are you on discord or anything?

**Comment by altmarkets** [comment]
Works great thanks @TheHolyRoger 
http://altmco.in/network

**Comment by TheHolyRoger** [comment]
To do: add setting to hide port info

**Comment by uaktags** [comment]
> Nice cheers @uaktags ! Are you on discord or anything?

@TheHolyRoger yea, i'm on discord Tags#5633

**Comment by uaktags** [comment]
Working good, tested with Vulcano and XPChain (neither coin I use anymore, just daemons that I've used in the past)
I'm thinking a cool thing to add would be a copy to clipboard and/or a download file.
Otherwise, this looks good to merge

**Pull request merged**
