### PR TITLE
Add TradeSatoshi exchange support

### PR DESCRIPTION
**Pull request by minkcrypto**
As per https://github.com/uaktags/iquidus-explorer-exchanges/tree/master/tradesatoshi

cc @uaktags @2g4y1

### CODE REVIEW

**Comment by TheHolyRoger** [comment]
Needs rebasing before I can merge

**Comment by TheHolyRoger** [comment]
working here https://explorer.cpuchain.org/markets/tradesatoshi

**Comment by minkcrypto** [comment]
One moment

**Comment by minkcrypto** [comment]
@TheHolyRoger Ah the repo is deleted so I will resubmit the PR

**Pull request closed without merging**
