### PR TITLE
Add uncaughtException event remove the lock file

### PR DESCRIPTION
**Pull request by AKIo0O**
image

### CODE REVIEW

**Comment by tofutim** [comment]
What are the risks of this fix? What does it mean, a transaction that has no vout?

**Comment by uaktags** [comment]
The exception has no negative sideeffects, and should be properly handled. I don't see any reason why the tx.vout is needed, can't think of any situation this would occur, but I guess it's just another reinforcement/sanity check.

**Comment by wh1tebeard** [comment]
I found an instance where 'coinbase' had been renamed in the coind output, so the object that was being returned had no vout as it was only a string...

**Comment by TheHolyRoger** [comment]
Uncaught exceptions need to be caught. But this will be addressed in upcoming per-coin commands

**Comment by forking-altcoins** [comment]
this error appears due to the use of the Z network in PIVX forks

**Pull request closed without merging**
