### PR TITLE
CSS: Address page QR code fix for mobile

### PR DESCRIPTION
**Pull request by TheHolyRoger**
The QR code for the address page was overlapping elements for me on mobile - this seems to fix it.

Can merge if it solves the problem for others!

### CODE REVIEW

**Comment by cryptozeny** [comment]
could you show us a screenshot? desktop and mobile both

**Comment by TheHolyRoger** [comment]
@cryptozeny try here: https://explorer.theholyroger.com/address/RogerV1FqDxkqj1PPxHbjmU4r3JAk5oB3U

**Comment by minkcrypto** [comment]
I suggest

1. We move the QR code location into the table just like @cryptozeny suggests,

And

2. Give a full responsive design to every elements on the frontend

**Comment by TheHolyRoger** [comment]
Fair enough, well I'm happy to help if anyone submits something else. I'm still tinkering with my other PRs for now

**Comment by TheHolyRoger** [comment]
@minkcrypto @cryptozeny 

Happy with how the QR code looks here now?

https://explorer.theholyroger.com/address/RkP4zXR1CrJTj7ELs9RBpEUonY5iDJv4UA

In this commit in the address history PR:

https://github.com/iquidus/explorer/pull/319/commits/22cf5b8ab54453bbc9633ed037b85c5dcbc657c2

**Comment by cryptozeny** [comment]
yeah looks better IMO

**Comment by TheHolyRoger** [comment]
Cool closing this PR then, the new fix is in https://github.com/iquidus/explorer/pull/319 :)

**Pull request closed without merging**
